apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: helloworld 
  namespace: default
spec:
  secretName: helloworld-tls-prod
  issuerRef:
    name: helloworld-letsncrypt-prod
  commonName: helloworld-v1.ghettolabs.io
  dnsNames:
  - helloworld-v1.ghettolabs.io
  - helloworld-v2.ghettolabs.io
  acme:
    config:
    - http01:
        ingress: helloworld 
      domains:
      - helloworld-v1.ghettolabs.io
      - helloworld-v2.ghettolabs.io
